version: '3'

# docker rm $(docker ps -a -q) && docker volume prune -f

services:
  mongodb:
    image: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=golang
    ports:
      - '27017-27019:27017-27019'